server:
  port: 8082
  servlet:
    context-path: /notification

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/notification_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true