server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
jwt:
  signerKey: "0VijumIKlJga2LjZOB6Duyc1hQiZTHRI/f1NZDsdTgfb/DOHMu2HVlCuX0hSzhWCg044+eq+khzk3ug8Sf7nSQ=="
app:
  services:
    profile: "http://localhost:8081/user_profile"