server:
  port: 8083
  servlet:
    context-path: /book

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/book_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


jwt:
  signerKey: "0VijumIKlJga2LjZOB6Duyc1hQiZTHRI/f1NZDsdTgfb/DOHMu2HVlCuX0hSzhWCg044+eq+khzk3ug8Sf7nSQ=="
