server:
  port: 8081
  servlet:
    context-path: /user_profile

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/user_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
